### ISSUE TITLE
More aspect ratios

### ISSUE THREAD

**Issue by retokromer** [ablwr/ablwr.github.io#3]
In the "4:3 family" there is also the "Academy" which comes in 1.375:1.

Classical "wide-screen" comes in three common flavours:
- 1.667:1
- 1.75:1
- 1.85:1

The "European" one is in fact just 5:3. Note that for long-time in Italy and for some time in the UK as well 1.75:1 has been used which BTW is actually the closest one to 16:9.

Therefore - still in an "European" context - you may say:
- silent: 1.333:1 = 4:3 = 32:24
- sound: 1.375:1 = 11:8 = 33:24
- wide-screen: 1.667:1 = 5:3 = 40:24

And there are worldwide a lot of other exotic aspect ratios as well... Hope this helps!

**Comment by ablwr** [comment]
Reto, always a wealth of knowledge (and well-versed in mathematical equations as well). I think we'll get to Academy in Pt. 2. Back when I was working with film, I was only working with newsreels and small-gauge -- which meant lots of 6:4, 4:3, 11:8 spot-checking going on.

My favorite format is still 12:1, Circle-Vision. ;)

**Comment by retokromer** [comment]
At the beginning of sound, before Academy, there was also a more square format (I don't remember if 1.20:1 or 1.19:1, or something like that). However the audience was not happy with.

In Switzerland there is (at least) one film in 3 x 1.33:1 i.e. 4:1: http://reto.ch/cgi-bin/filmo.pl?what=4,%20croissance&where=title

And also (at least) one video in 9:16: http://reto.ch/cgi-bin/filmo.pl?what=aus%20dem%20nichts&where=title

My favourite is the golden ratio ;-)

**Comment by ektachrome3** [comment]
Just a note to say that I am pretty sure that white flash in the Tina Knowles video is from a still photography camera's flash going off while they were recording.

**Comment by ablwr** [comment]
Hey, thanks @ektachrome3!
